# -*- coding: utf-8 -*-
"""Predicting_Salary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ds3wKKVdATtumkeEoOA3vrMFJhHkypZF

**Importing Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""**Importing Dataset**"""

dataset= pd.read_csv("Salary_Data.csv")
x= dataset.iloc[:, :-1]
y=dataset.iloc[:, -1]

dataset.head() # To check if the data is loaded on not

"""**Seperate TrainSet and TestSet**"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train , y_test = train_test_split(x, y, test_size=0.2 , random_state=0)

"""**Training the Simple Linear Regression Model on Training Set**"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

"""**Predicting TestSet**"""

y_pred = regressor.predict(x_test)

"""**Visualising the Training Set**"""

plt.scatter(x_train , y_train , color='red')
plt.plot(x_train , regressor.predict(x_train), color='blue')
plt.title("Salary vs Experience [Training]")
plt.xlabel("Experience")
plt.ylabel("Salary")

"""**Visualising the Test Set**"""



plt.scatter(x_test , y_test , color='red')
plt.plot(x_train , regressor.predict(x_train), color='blue')
plt.title("Salary vs Experience [Testing]")
plt.xlabel("Experience")
plt.ylabel("Salary")