# -*- coding: utf-8 -*-
"""Predicting _Profit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1doiF68fs1agECMLK5Rk07qt5ox0sAV0q

**Importing Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""**Importing Dataset**"""

dataset= pd.read_csv("50_Startups.csv")
x= dataset.iloc[:, :-1]
y=dataset.iloc[:, -1]

print (x)

"""**Encoding Categorical Data**"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct= ColumnTransformer( transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

print (x)

"""**Seperate Test Set and Training Set**"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train , y_test = train_test_split(x, y, test_size=0.2 , random_state=0)

"""**Training the Multiple Linear Regression Model**"""

from sklearn.linear_model import LinearRegression
regressor= LinearRegression()
regressor.fit(x_train, y_train)

"""**Predicting the Test Set Result**"""

y_pred= regressor.predict(x_test)
np.set_printoptions(precision=2)

print (y_pred)

print(y_test)