# -*- coding: utf-8 -*-
"""Predict_the_Salary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16VZi3ms7UXAs-NQXm4OK5vd0Avdtnvs0

**Importing the Libraries**
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""**Import DataSet**"""

dataset= pd.read_csv("Position_Salaries.csv")
x= dataset.iloc[:, 1:-1].values
y= dataset.iloc[:, -1].values

print (x)
print(y)

"""**Training using Linear Regression**"""

from sklearn.linear_model import LinearRegression
regressor_linear = LinearRegression()
regressor_linear.fit(x,y)

"""**Training using Polynomial Regression Model**"""

from sklearn.preprocessing import PolynomialFeatures
regressor_poly = PolynomialFeatures(degree=4)
x_poly =regressor_poly.fit_transform(x)
regressor_linear_2 = LinearRegression()
regressor_linear_2.fit(x_poly, y)

"""**Visualsing the Linear Regression**"""

plt.scatter(x,y, color='red')
plt.plot(x, regressor_linear.predict(x), color='blue')
plt.title('Linear Model')
plt.xlabel("Level")
plt.ylabel("Salary")

"""**Visualising the Polynomial Regression Result**"""

plt.scatter(x,y, color='red')
plt.plot(x, regressor_linear_2.predict(x_poly), color='blue')
plt.title('Linear Model')
plt.xlabel("Level")
plt.ylabel("Salary")

"""Predicting the Salary with Linear Regression"""

regressor_linear.predict([[6.5]])

"""Predicting the Salary with Polynomial Regression"""

regressor_linear_2.predict(regressor_poly.fit_transform([[6.5]]))